# Generated by Django 3.2 on 2022-07-17 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_rating_club'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comuna',
            options={'verbose_name': 'Comuna', 'verbose_name_plural': 'Comunas'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
    ]
