# Generated by Django 3.2 on 2022-07-17 21:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220717_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='description',
            field=ckeditor.fields.RichTextField(default='aqui texto'),
        ),
    ]
