# Generated by Django 3.2 on 2022-07-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_clubes_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubes',
            name='imagen_perfil',
            field=models.URLField(default='aqui imagen perfil', max_length=400),
        ),
    ]
